
import React, { useState } from 'react';
import { BarChart3, Download, FileText, Users, Calendar, Table, Printer, UserCheck } from 'lucide-react';
import { Expense, Staff, AdvanceLog, Attendance } from '../types';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Cell } from 'recharts';

interface ReportsProps {
  expenses: Expense[];
  staffList: Staff[];
  advances: AdvanceLog[];
  attendanceList: Attendance[];
}

const ReportsView: React.FC<ReportsProps> = ({ expenses, staffList, advances, attendanceList }) => {
  const [reportStartDate, setReportStartDate] = useState('');
  const [reportEndDate, setReportEndDate] = useState('');

  const approvedExpenses = expenses.filter(e => !e.isDeleted && e.status === 'APPROVED');
  
  // Chart Data Preparation (Staff-wise expenses) - Overall
  const staffData = staffList.map(s => {
    const total = approvedExpenses.filter(e => e.staffId === s.id).reduce((sum, e) => sum + e.amount, 0);
    return { name: s.name, amount: total };
  }).filter(d => d.amount > 0);

  const COLORS = ['#6366f1', '#8b5cf6', '#ec4899', '#f43f5e', '#f59e0b', '#10b981'];

  // Attendance Report Generator
  const generateAttendanceReport = () => {
    const start = reportStartDate ? new Date(reportStartDate).setHours(0, 0, 0, 0) : 0;
    const end = reportEndDate ? new Date(reportEndDate).setHours(23, 59, 59, 999) : Number.MAX_VALUE;

    // Filter
    const filteredAttendance = attendanceList.filter(a => {
      const d = new Date(a.date).getTime();
      return d >= start && d <= end;
    }).sort((a, b) => new Date(a.checkInTime).getTime() - new Date(b.checkInTime).getTime());

    if (filteredAttendance.length === 0) {
      alert("নির্বাচিত তারিখের মধ্যে কোনো হাজিরা ডাটা পাওয়া যায়নি।");
      return;
    }

    // Summary Calculation
    const summary = staffList.map(staff => {
      const records = filteredAttendance.filter(a => a.staffId === staff.id);
      return {
        name: staff.name,
        present: records.filter(a => a.status === 'PRESENT' || a.status === 'LATE').length, // Total present
        late: records.filter(a => a.status === 'LATE').length,
        totalRecords: records.length
      };
    }).filter(s => s.totalRecords > 0);

    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    const htmlContent = `
      <!DOCTYPE html>
      <html lang="bn">
      <head>
        <meta charset="UTF-8">
        <title>Attendance Report - Depend Sourcing Ltd</title>
        <script src="https://cdn.tailwindcss.com"></script>
        <link href="https://fonts.googleapis.com/css2?family=Hind+Siliguri:wght@300;400;500;600;700&display=swap" rel="stylesheet">
        <style>
          body { font-family: 'Hind Siliguri', sans-serif; -webkit-print-color-adjust: exact; }
          @page { size: A4; margin: 15mm; }
          .no-break { break-inside: avoid; }
        </style>
      </head>
      <body class="bg-white text-gray-800">
        <div class="max-w-[210mm] mx-auto p-4">
          <!-- Header -->
          <div class="flex justify-between items-start mb-8 border-b-2 border-green-600 pb-6">
            <div>
               <h1 class="text-3xl font-black text-green-800 tracking-tight">Depend Sourcing Ltd.</h1>
               <p class="text-sm text-gray-500 mt-1 font-medium">Monthly Attendance Report</p>
               <div class="mt-4 text-xs text-gray-500 space-y-0.5">
                 <p><span class="font-bold">Generated By:</span> System Admin</p>
                 <p><span class="font-bold">Print Date:</span> ${new Date().toLocaleDateString('bn-BD', { dateStyle: 'full' })}</p>
               </div>
            </div>
            <div class="text-right">
              <h2 class="text-5xl font-black text-gray-100 uppercase tracking-widest absolute right-10 top-10 pointer-events-none select-none">ATTENDANCE</h2>
              <div class="relative z-10">
                <p class="text-green-600 font-bold text-lg uppercase tracking-wider">Staff Attendance Log</p>
                <div class="text-xs text-gray-500 mt-1 bg-gray-50 px-3 py-1 rounded-md inline-block border border-gray-100">
                  <span class="font-bold">Period:</span> ${reportStartDate ? new Date(reportStartDate).toLocaleDateString('bn-BD') : 'Start'} — ${reportEndDate ? new Date(reportEndDate).toLocaleDateString('bn-BD') : 'Current'}
                </div>
              </div>
            </div>
          </div>

          <!-- Summary Table -->
          <div class="mb-8 no-break">
             <h3 className="font-bold text-gray-700 mb-3 border-l-4 border-green-500 pl-2">Attendance Summary</h3>
             <table class="w-full text-left border-collapse border border-gray-200">
                <thead>
                   <tr class="bg-gray-50 text-xs font-bold text-gray-600 uppercase">
                      <th class="p-2 border border-gray-200">Staff Name</th>
                      <th class="p-2 border border-gray-200 text-center">Total Present (Days)</th>
                      <th class="p-2 border border-gray-200 text-center">Late (Days)</th>
                   </tr>
                </thead>
                <tbody class="text-sm">
                   ${summary.map(s => `
                      <tr>
                         <td class="p-2 border border-gray-200 font-bold">${s.name}</td>
                         <td class="p-2 border border-gray-200 text-center">${s.present}</td>
                         <td class="p-2 border border-gray-200 text-center text-red-600 font-bold">${s.late > 0 ? s.late : '-'}</td>
                      </tr>
                   `).join('')}
                </tbody>
             </table>
          </div>

          <!-- Detailed Log Table -->
          <h3 className="font-bold text-gray-700 mb-3 border-l-4 border-green-500 pl-2 mt-6">Detailed Daily Log</h3>
          <table class="w-full text-left border-collapse mb-8">
            <thead>
              <tr class="bg-green-800 text-white text-[10px] uppercase tracking-wider">
                <th class="p-3 rounded-tl-lg font-bold">Date</th>
                <th class="p-3 font-bold">Staff Name</th>
                <th class="p-3 font-bold text-center">Check-In</th>
                <th class="p-3 font-bold text-center">Check-Out</th>
                <th class="p-3 font-bold text-center">Status</th>
                <th class="p-3 font-bold text-right rounded-tr-lg">Location</th>
              </tr>
            </thead>
            <tbody class="text-sm">
              ${filteredAttendance.map((a, index) => `
                <tr class="${index % 2 === 0 ? 'bg-white' : 'bg-green-50/30'} border-b border-gray-100 no-break">
                  <td class="p-3 whitespace-nowrap text-xs font-bold text-gray-600">${new Date(a.date).toLocaleDateString('bn-BD')}</td>
                  <td class="p-3 font-bold text-gray-800 text-xs">${a.staffName}</td>
                  <td class="p-3 text-center text-xs font-medium">${new Date(a.checkInTime).toLocaleTimeString('bn-BD', {hour:'2-digit', minute:'2-digit'})}</td>
                  <td class="p-3 text-center text-xs text-gray-500">${a.checkOutTime ? new Date(a.checkOutTime).toLocaleTimeString('bn-BD', {hour:'2-digit', minute:'2-digit'}) : '--'}</td>
                  <td class="p-3 text-center">
                    <span class="px-2 py-0.5 rounded text-[9px] font-black uppercase tracking-tight ${
                      a.status === 'LATE' ? 'bg-orange-100 text-orange-700' : 'bg-green-100 text-green-700'
                    }">
                      ${a.status}
                    </span>
                  </td>
                  <td class="p-3 text-right text-[10px] text-gray-500 truncate max-w-[150px]">${a.location?.address || 'N/A'}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>

          <!-- Footer -->
          <div class="mt-auto pt-8 border-t border-gray-200 flex justify-between items-end text-xs text-gray-400 no-break">
             <div>
                <p class="font-bold text-gray-500">Depend Sourcing Ltd.</p>
                <p>© ${new Date().getFullYear()} Confidential HR Document.</p>
             </div>
             <div class="text-right">
               <div class="h-16 flex flex-col justify-end">
                  <div class="w-40 border-b border-gray-300 mb-2"></div>
               </div>
               <p class="font-bold uppercase tracking-wider text-[10px]">Authorized Signature</p>
             </div>
          </div>
        </div>
        <script>
          window.onload = () => {
             setTimeout(() => {
                window.print();
             }, 500);
          }
        </script>
      </body>
      </html>
    `;

    printWindow.document.write(htmlContent);
    printWindow.document.close();
  };

  // Premium PDF Report Generator (Financial)
  const generatePDFReport = () => {
    // 1. Filter Expenses and Advances by Date
    const start = reportStartDate ? new Date(reportStartDate).setHours(0, 0, 0, 0) : 0;
    const end = reportEndDate ? new Date(reportEndDate).setHours(23, 59, 59, 999) : Number.MAX_VALUE;

    const filteredExpenses = expenses.filter(e => {
      if (e.isDeleted) return false;
      const d = new Date(e.createdAt).getTime();
      return d >= start && d <= end;
    });

    const filteredAdvances = advances.filter(a => {
      if (a.isDeleted) return false;
      const d = new Date(a.date).getTime();
      return d >= start && d <= end;
    });

    if (filteredExpenses.length === 0 && filteredAdvances.length === 0) {
      alert("নির্বাচিত তারিখের মধ্যে কোনো ডাটা পাওয়া যায়নি।");
      return;
    }

    // Merge and Sort by Date
    const allTransactions = [
      ...filteredExpenses.map(e => ({
        id: e.id,
        date: e.createdAt,
        type: 'BILL',
        staffName: e.staffName,
        description: e.reason,
        amount: e.amount,
        status: e.status
      })),
      ...filteredAdvances.map(a => ({
        id: a.id,
        date: a.date,
        type: 'ADVANCE',
        staffName: a.staffName,
        description: (a.type === 'SALARY' ? '[SALARY ADV] ' : '') + (a.note || 'Advance Payment'),
        amount: a.amount,
        status: 'PAID'
      }))
    ].sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime());

    const totalExpenseAmount = filteredExpenses.reduce((sum, e) => sum + e.amount, 0);
    const totalApproved = filteredExpenses.filter(e => e.status === 'APPROVED').reduce((sum, e) => sum + e.amount, 0);
    const totalAdvanceGiven = filteredAdvances.reduce((sum, a) => sum + a.amount, 0);

    // Open new window for print view
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    const htmlContent = `
      <!DOCTYPE html>
      <html lang="bn">
      <head>
        <meta charset="UTF-8">
        <title>Ledger Report - Depend Sourcing Ltd</title>
        <script src="https://cdn.tailwindcss.com"></script>
        <link href="https://fonts.googleapis.com/css2?family=Hind+Siliguri:wght@300;400;500;600;700&display=swap" rel="stylesheet">
        <style>
          body { font-family: 'Hind Siliguri', sans-serif; -webkit-print-color-adjust: exact; }
          @page { size: A4; margin: 15mm; }
          .no-break { break-inside: avoid; }
        </style>
      </head>
      <body class="bg-white text-gray-800">
        <div class="max-w-[210mm] mx-auto p-4">
          <!-- Header -->
          <div class="flex justify-between items-start mb-8 border-b-2 border-indigo-600 pb-6">
            <div>
               <h1 class="text-3xl font-black text-indigo-900 tracking-tight">Depend Sourcing Ltd.</h1>
               <p class="text-sm text-gray-500 mt-1 font-medium">Billing & Expense Management Center</p>
               <div class="mt-4 text-xs text-gray-500 space-y-0.5">
                 <p><span class="font-bold">Generated By:</span> System Admin</p>
                 <p><span class="font-bold">Print Date:</span> ${new Date().toLocaleDateString('bn-BD', { dateStyle: 'full' })}</p>
               </div>
            </div>
            <div class="text-right">
              <h2 class="text-5xl font-black text-gray-100 uppercase tracking-widest absolute right-10 top-10 pointer-events-none select-none">LEDGER</h2>
              <div class="relative z-10">
                <p class="text-indigo-600 font-bold text-lg uppercase tracking-wider">Statement of Accounts</p>
                <div class="text-xs text-gray-500 mt-1 bg-gray-50 px-3 py-1 rounded-md inline-block border border-gray-100">
                  <span class="font-bold">Period:</span> ${reportStartDate ? new Date(reportStartDate).toLocaleDateString('bn-BD') : 'Start'} — ${reportEndDate ? new Date(reportEndDate).toLocaleDateString('bn-BD') : 'Current'}
                </div>
              </div>
            </div>
          </div>

          <!-- Summary Cards -->
          <div class="grid grid-cols-3 gap-4 mb-8">
            <div class="bg-gray-50 p-4 rounded-xl border border-gray-200">
               <p class="text-[9px] text-gray-500 uppercase font-black tracking-widest">Total Bill Submitted</p>
               <p class="text-2xl font-black text-gray-800 mt-1">৳ ${totalExpenseAmount.toLocaleString()}</p>
            </div>
            <div class="bg-indigo-50 p-4 rounded-xl border border-indigo-100">
               <p class="text-[9px] text-indigo-600 uppercase font-black tracking-widest">Total Approved (Paid)</p>
               <p class="text-2xl font-black text-indigo-700 mt-1">৳ ${totalApproved.toLocaleString()}</p>
            </div>
            <div class="bg-blue-50 p-4 rounded-xl border border-blue-100">
               <p class="text-[9px] text-blue-600 uppercase font-black tracking-widest">Total Advance Given</p>
               <p class="text-2xl font-black text-blue-700 mt-1">৳ ${totalAdvanceGiven.toLocaleString()}</p>
            </div>
          </div>

          <!-- Table -->
          <table class="w-full text-left border-collapse mb-8">
            <thead>
              <tr class="bg-indigo-900 text-white text-[10px] uppercase tracking-wider">
                <th class="p-3 rounded-tl-lg font-bold">SL</th>
                <th class="p-3 font-bold">Date</th>
                <th class="p-3 font-bold">Type</th>
                <th class="p-3 font-bold">Staff Name</th>
                <th class="p-3 font-bold w-1/4">Description</th>
                <th class="p-3 font-bold text-center">Status</th>
                <th class="p-3 font-bold text-right rounded-tr-lg">Amount</th>
              </tr>
            </thead>
            <tbody class="text-sm">
              ${allTransactions.map((t, index) => `
                <tr class="${index % 2 === 0 ? 'bg-white' : 'bg-slate-50'} border-b border-gray-100 no-break">
                  <td class="p-3 font-medium text-gray-400">${index + 1}</td>
                  <td class="p-3 whitespace-nowrap text-xs">${new Date(t.date).toLocaleDateString('bn-BD')}</td>
                  <td class="p-3">
                    <span class="px-2 py-0.5 rounded text-[9px] font-black uppercase tracking-tight ${t.type === 'ADVANCE' ? 'bg-blue-100 text-blue-700' : 'bg-gray-100 text-gray-600'}">
                      ${t.type === 'ADVANCE' ? 'ADVANCE' : 'EXPENSE'}
                    </span>
                  </td>
                  <td class="p-3 font-bold text-gray-700 text-xs">${t.staffName}</td>
                  <td class="p-3 text-gray-600 text-xs">${t.description}</td>
                  <td class="p-3 text-center">
                    <span class="px-2 py-0.5 rounded text-[9px] font-black uppercase tracking-tight ${
                      t.status === 'APPROVED' || t.status === 'PAID' ? 'bg-green-100 text-green-700' : 
                      t.status === 'PENDING' ? 'bg-orange-100 text-orange-700' : 
                      t.status === 'REJECTED' ? 'bg-red-100 text-red-700' : 'bg-blue-100 text-blue-700'
                    }">
                      ${t.status}
                    </span>
                  </td>
                  <td class="p-3 text-right font-bold ${t.type === 'ADVANCE' ? 'text-blue-700' : 'text-gray-800'}">৳ ${t.amount.toLocaleString()}</td>
                </tr>
              `).join('')}
            </tbody>
            <tfoot>
               <tr class="bg-gray-100 text-gray-800 font-bold text-xs">
                 <td colspan="6" class="p-3 text-right uppercase tracking-wider">Net Bill Approved (Expense)</td>
                 <td class="p-3 text-right">৳ ${totalApproved.toLocaleString()}</td>
               </tr>
               <tr class="bg-gray-100 text-blue-700 font-bold text-xs">
                 <td colspan="6" class="p-3 text-right uppercase tracking-wider">Net Advance Given</td>
                 <td class="p-3 text-right rounded-br-lg">৳ ${totalAdvanceGiven.toLocaleString()}</td>
               </tr>
            </tfoot>
          </table>

          <!-- Footer -->
          <div class="mt-auto pt-8 border-t border-gray-200 flex justify-between items-end text-xs text-gray-400 no-break">
             <div>
                <p class="font-bold text-gray-500">Depend Sourcing Ltd.</p>
                <p>© ${new Date().getFullYear()} Internal Document. Confidential.</p>
             </div>
             <div class="text-right">
               <div class="h-16 flex flex-col justify-end">
                  <div class="w-40 border-b border-gray-300 mb-2"></div>
               </div>
               <p class="font-bold uppercase tracking-wider text-[10px]">Authorized Signature</p>
             </div>
          </div>
        </div>
        <script>
          window.onload = () => {
             setTimeout(() => {
                window.print();
             }, 500);
          }
        </script>
      </body>
      </html>
    `;

    printWindow.document.write(htmlContent);
    printWindow.document.close();
  };

  return (
    <div className="space-y-8">
      {/* Report Control Panel */}
      <div className="bg-white p-6 rounded-2xl shadow-sm border border-gray-100">
        <h3 className="font-bold text-gray-800 mb-4 flex items-center gap-2">
          <FileText className="w-5 h-5 text-indigo-600" />
          রিপোর্ট জেনারেট করুন
        </h3>
        
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4 items-end">
          <div>
            <label className="block text-xs font-bold text-gray-400 uppercase tracking-widest mb-2">শুরুর তারিখ</label>
            <input 
              type="date" 
              className="w-full px-4 py-2 border border-gray-200 rounded-xl focus:ring-2 focus:ring-indigo-500 outline-none"
              value={reportStartDate}
              onChange={(e) => setReportStartDate(e.target.value)}
            />
          </div>
          <div>
            <label className="block text-xs font-bold text-gray-400 uppercase tracking-widest mb-2">শেষ তারিখ</label>
            <input 
              type="date" 
              className="w-full px-4 py-2 border border-gray-200 rounded-xl focus:ring-2 focus:ring-indigo-500 outline-none"
              value={reportEndDate}
              onChange={(e) => setReportEndDate(e.target.value)}
            />
          </div>
          <button 
            onClick={generatePDFReport}
            className="w-full bg-indigo-600 text-white py-2.5 rounded-xl font-bold hover:bg-indigo-700 transition-all flex items-center justify-center gap-2 shadow-lg shadow-indigo-100 active:scale-95"
          >
            <Printer className="w-5 h-5" />
            ফিনান্সিয়াল রিপোর্ট (PDF)
          </button>
          <button 
            onClick={generateAttendanceReport}
            className="w-full bg-green-600 text-white py-2.5 rounded-xl font-bold hover:bg-green-700 transition-all flex items-center justify-center gap-2 shadow-lg shadow-green-100 active:scale-95"
          >
            <UserCheck className="w-5 h-5" />
            হাজিরা রিপোর্ট (PDF)
          </button>
        </div>
        <p className="text-xs text-gray-400 mt-3 flex items-center gap-1">
          <Users className="w-3 h-3" /> 
          রিপোর্টের ধরণ অনুযায়ী বাটন সিলেক্ট করুন।
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Chart Area */}
        <div className="lg:col-span-2 bg-white p-6 rounded-2xl shadow-sm border border-gray-100">
          <div className="flex items-center justify-between mb-8">
             <h3 className="font-bold text-gray-800 flex items-center gap-2">
               <BarChart3 className="w-5 h-5 text-indigo-500" />
               ব্যক্তি-ভিত্তিক খরচের পরিসংখ্যান (সর্বমোট)
             </h3>
          </div>
          <div className="h-80 w-full">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={staffData}>
                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f3f4f6" />
                <XAxis dataKey="name" axisLine={false} tickLine={false} tick={{fontSize: 12, fill: '#9ca3af'}} />
                <YAxis axisLine={false} tickLine={false} tick={{fontSize: 12, fill: '#9ca3af'}} />
                <Tooltip 
                  cursor={{fill: '#f9fafb'}}
                  contentStyle={{borderRadius: '12px', border: 'none', boxShadow: '0 10px 15px -3px rgb(0 0 0 / 0.1)'}}
                />
                <Bar dataKey="amount" radius={[8, 8, 0, 0]} barSize={40}>
                  {staffData.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Analytics Card */}
        <div className="bg-white p-6 rounded-2xl shadow-sm border border-gray-100">
           <h3 className="font-bold text-gray-800 mb-6">সিস্টেম অ্যানালিটিক্স</h3>
           <div className="space-y-6">
              <div className="flex items-center justify-between p-4 bg-gray-50 rounded-xl">
                 <div className="flex items-center gap-3">
                   <Users className="w-5 h-5 text-indigo-600" />
                   <span className="text-sm font-medium text-gray-600">মোট স্টাফ বিল</span>
                 </div>
                 <span className="font-bold text-gray-800">{staffData.length} জন</span>
              </div>
              <div className="flex items-center justify-between p-4 bg-gray-50 rounded-xl">
                 <div className="flex items-center gap-3">
                   <Calendar className="w-5 h-5 text-indigo-600" />
                   <span className="text-sm font-medium text-gray-600">গড় দৈনিক খরচ</span>
                 </div>
                 <span className="font-bold text-gray-800">৳ {(approvedExpenses.reduce((s,e)=>s+e.amount,0) / 30).toFixed(0)}</span>
              </div>
           </div>
           <div className="mt-8 p-4 bg-indigo-600 rounded-2xl text-white">
              <p className="text-xs text-indigo-100 uppercase font-bold mb-1">সর্বোচ্চ খরচকারী</p>
              <h4 className="text-xl font-black">
                {staffData.length > 0 ? staffData.sort((a,b) => b.amount - a.amount)[0].name : '--'}
              </h4>
              <p className="text-sm text-indigo-100 mt-2">মোট ৳ {staffData.length > 0 ? staffData.sort((a,b) => b.amount - a.amount)[0].amount.toLocaleString() : '০'}</p>
           </div>
        </div>
      </div>
    </div>
  );
};

export default ReportsView;
